# Generated by Django 6.0.3 on 2026-04-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
        ('core', '0004_attachment'),
    ]

    operations = [
    ]
