# Generated by Django 6.0.5 on 2026-05-05 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remark',
            old_name='user',
            new_name='admin',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
